### ISSUE TITLE
H5打包时出错了

### ISSUE THREAD

**Issue by hnty545** [bigmeow/axios-miniprogram-adapter#1]
### 问题是什么
"mpvue": "^1.0.18",
"axios": "^0.18.0",
"axios-miniprogram-adapter": "^0.2.2",
使用以上库编译小程序，但是报如下错误

ERROR in ./node_modules/axios-miniprogram-adapter/dist/index.esm.js
Module not found: Error: Can't resolve 'axios/lib/core/createError' in 'C:\_develop\workspace_wx\vue-smart-publish-wx\node_modules\axios-miniprogram-adapter\dist'
 @ ./node_modules/axios-miniprogram-adapter/dist/index.esm.js 11:0-53
 @ ./src/net/NetHelper.js
 @ ./node_modules/mpvue-entry/dist/viewsBaseHomeHome.js

ERROR in ./node_modules/axios-miniprogram-adapter/dist/index.esm.js
Module not found: Error: Can't resolve 'axios/lib/core/settle' in 'C:\_develop\workspace_wx\vue-smart-publish-wx\node_modules\axios-miniprogram-adapter\dist'
 @ ./node_modules/axios-miniprogram-adapter/dist/index.esm.js 9:0-43
 @ ./src/net/NetHelper.js
 @ ./node_modules/mpvue-entry/dist/viewsBaseHomeHome.js

ERROR in ./node_modules/axios-miniprogram-adapter/dist/index.esm.js
Module not found: Error: Can't resolve 'axios/lib/helpers/buildURL' in 'C:\_develop\workspace_wx\vue-smart-publish-wx\node_modules\axios-miniprogram-adapter\dist'
 @ ./node_modules/axios-miniprogram-adapter/dist/index.esm.js 10:0-50
 @ ./src/net/NetHelper.js
 @ ./node_modules/mpvue-entry/dist/viewsBaseHomeHome.js

ERROR in ./node_modules/axios-miniprogram-adapter/dist/index.esm.js
Module not found: Error: Can't resolve 'axios/lib/utils' in 'C:\_develop\workspace_wx\vue-smart-publish-wx\node_modules\axios-miniprogram-adapter\dist'
 @ ./node_modules/axios-miniprogram-adapter/dist/index.esm.js 8:0-36
 @ ./src/net/NetHelper.js
 @ ./node_modules/mpvue-entry/dist/viewsBaseHomeHome.js

  Build failed with errors.

### 环境
h5打包时出错了

### 在线例子
如果有请提供在线例子

### 其他
其他信息

**Comment by hnty545** [comment]
因为用了webpack的别名编译，去掉就没报了
axios: 'axios/dist/axios

**Comment by hnty545** [comment]
去掉又不能用mpvue了，好像是不能一起用

**Comment by bigmeow** [comment]
我感觉你需要看下注意事项，更改下对应的webpack 配置
https://github.com/bigMeow/axios-miniprogram-adapter/blob/master/doc/api.md
