### ISSUE TITLE
微信小程序中使用npm的情况下 axios找不到

### ISSUE THREAD

**Issue by maplehsu** [bigmeow/axios-miniprogram-adapter#10]
微信小程序中使用npm的情况下
不在app.js 或者 pages目录下面的js 引入 会报错 找不到 axios
我在pages目录同级建立一个api的目录在里面引入 
import axios from 'axios'
import mpAdapter from 'axios-miniprogram-adapter'

axios找不到请问这个必须
import axios from '你的目录/axios.js'
import mpAdapter from '你的目录/axios-miniprogram-adapter.js'
axios.defaults.adapter = mpAdapter
这样吗？ 这样是可以的

**Comment by bigmeow** [comment]
两个都要安装:
```
npm i  axios  axios-miniprogram-adapter
```
然后点击小程序的 "构建npm"

**Comment by maplehsu** [comment]
都安装了一样不行。只要不在app.js 里面 你可以尝试一下 我在小程序根目录创建一个api文件里面写了一个axios.js 在这个文件里面引入不行的
![Uploading image.png…]()
