### ISSUE TITLE
关闭ES6 to ES5 就会报错，有解决办法吗

### ISSUE THREAD

**Issue by neozhu** [bigmeow/axios-miniprogram-adapter#15]
### 问题
因为我需要原生支持 async/await 关闭了ES6 to ES5 ，但这样引用就会报错。
但打开了ES6 to ES5 async/await 又不能用，那么我用axios就没什么意义了
有什么好的解决办法吗

### 环境
微信小程序开发工具

**Comment by bigmeow** [comment]
@neozhu 
你是原生小程序开发、没有用任何框架还是用了mpvue、megalo这类框架？
如果是纯原生小程序开发，你想使用async/await 则必须开启es6 to es5 并且打开增强编译开关，不知道你为什么反着来；
此库npm已经提供了es5版本的代码，默认情况下使用小程序开发者工具自带的Npm安装的就是es5的代码。
不知道你说的引用报错具体是什么错误

**Comment by neozhu** [comment]
谢谢回复，问题找到了，实在自己太菜了，开启时es6 to es5 还要开启增强编译。现在问题解决了
