### ISSUE TITLE
我以为是脱离了微信小程序限制的adapter

### ISSUE THREAD

**Issue by yhuaqiang** [bigmeow/axios-miniprogram-adapter#16]
### 问题是什么
小程序的request不允许设置host和referer,请问有办法绕过去吗?

### 环境
- 手机: 小米6
- 系统：安卓7.1.1
- 微信版本：6.7.0
- axios-miniprogram-adapter版本：0.1.0
- 其他版本信息

### 在线例子
如果有请提供在线例子

### 其他
其他信息

**Comment by bigmeow** [comment]
底层还是调用的wx.request的api,只是抹平了语法差异；翻了下文档，referer是不支持设置的。如果需要设置这个来绕过别人后端的验证，你得在自己的后端做一层代理转发
![image](https://user-images.githubusercontent.com/10484248/76580896-7da1f380-650c-11ea-960e-12d56c488a4e.png)

**Comment by yhuaqiang** [comment]
还有host也不支持发自我的iPhone------------------ 原始邮件 ------------------发件人: 大喵  <notifications@github.com>发送时间: 2020年3月13日 09:27收件人: bigmeow/axios-miniprogram-adapter <axios-miniprogram-adapter@noreply.github.com>抄送: yhuaqiang <yhuaqiang@163.com>, Author <author@noreply.github.com>主题: 回复：[bigmeow/axios-miniprogram-adapter] 我以为是脱离了微信小程序限制的adapter (#16)
底层还是调用的wx.request的api,只是抹平了语法差异；翻了下文档，referer是不支持设置的。如果需要设置这个来绕过别人后端的验证，你得在自己的后端做一层代理转发


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bigmeow/axios-miniprogram-adapter/issues/16#issuecomment-598504240",
"url": "https://github.com/bigmeow/axios-miniprogram-adapter/issues/16#issuecomment-598504240",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yhuaqiang** [comment]
那如果只想在前端实现，有办法吗？发自我的iPhone------------------ 原始邮件 ------------------发件人: 大喵  <notifications@github.com>发送时间: 2020年3月13日 09:27收件人: bigmeow/axios-miniprogram-adapter <axios-miniprogram-adapter@noreply.github.com>抄送: yhuaqiang <yhuaqiang@163.com>, Author <author@noreply.github.com>主题: 回复：[bigmeow/axios-miniprogram-adapter] 我以为是脱离了微信小程序限制的adapter (#16)
底层还是调用的wx.request的api,只是抹平了语法差异；翻了下文档，referer是不支持设置的。如果需要设置这个来绕过别人后端的验证，你得在自己的后端做一层代理转发


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bigmeow/axios-miniprogram-adapter/issues/16#issuecomment-598504240",
"url": "https://github.com/bigmeow/axios-miniprogram-adapter/issues/16#issuecomment-598504240",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
