### ISSUE TITLE
钉钉小程序中使用put方法，但是设置Content-Type无效

### ISSUE THREAD

**Issue by jinyaoye23** [bigmeow/axios-miniprogram-adapter#17]
钉钉小程序中使用put方法，并设置headers的Content-Type为application/json, 但是设置Content-Type无效, 在浏览器上看到的是x-www-form-urlencoded

**Comment by Jonh-Son** [comment]
楼主解决这个问题了吗。钉钉小程序目前暂不支持除POST、GET之外的请求方式。并且钉钉默认Content-Type为“x-www-form-urlencoded”。我在axios.create() 中放置了Content-Type为“application/json”的headers, 但未起作用，只能用钉钉原生的了。害，钉钉小程序真头大

**Comment by jinyaoye23** [comment]
我们没有用put请求，时间成本太大还不知道能不能解决，就让后端把接口改为了post请求了，钉钉小程序怎么说呢，挺让人抓狂的

**Comment by jinyaoye23** [comment]
> 楼主解决这个问题了吗。钉钉小程序目前暂不支持除POST、GET之外的请求方式。并且钉钉默认Content-Type为“x-www-form-urlencoded”。我在axios.create() 中放置了Content-Type为“application/json”的headers, 但未起作用，只能用钉钉原生的了。害，钉钉小程序真头大
> ![image](https://user-images.githubusercontent.com/44459165/85014764-75a3c080-b199-11ea-811e-def5259879d0.png)

我们没有用put请求，时间成本太大还不知道能不能解决，就让后端把接口改为了post请求了，钉钉小程序怎么说呢，挺让人抓狂的

**Comment by bigmeow** [comment]
已修复 https://github.com/bigmeow/axios-miniprogram-adapter/commit/2bcc95cd040c35e196b7cf40b28ccb49ffd44a1b
