### ISSUE TITLE
加载就出错

### ISSUE THREAD

**Issue by meikang123** [bigmeow/axios-miniprogram-adapter#2]
### 问题是什么
问题的具体描述，尽量详细

### 环境
- 手机: 小米6
- 系统：安卓7.1.1
- 微信版本：6.7.0
- axios-miniprogram-adapter版本：0.1.0
- 其他版本信息

### 在线例子
如果有请提供在线例子

### 其他
其他信息
ERROR in ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
Module not found: Error: Can't resolve 'http' in 'D:\megalo\my-megalo-pro\node_modules\_axios@0.18.0@axios\lib\adapters'
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js 6:11-26
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js
Module not found: Error: Can't resolve 'http' in 'D:\megalo\my-megalo-pro\node_modules\_follow-redirects@1.7.0@follow-redirects'
 @ ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js 7:11-26
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
Module not found: Error: Can't resolve 'https' in 'D:\megalo\my-megalo-pro\node_modules\_axios@0.18.0@axios\lib\adapters'
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js 7:12-28
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js
Module not found: Error: Can't resolve 'https' in 'D:\megalo\my-megalo-pro\node_modules\_follow-redirects@1.7.0@follow-redirects'
 @ ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js 8:12-28
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_supports-color@6.1.0@supports-color/index.js
Module not found: Error: Can't resolve 'os' in 'D:\megalo\my-megalo-pro\node_modules\_supports-color@6.1.0@supports-color'
 @ ./node_modules/_supports-color@6.1.0@supports-color/index.js 3:9-22
 @ ./node_modules/_debug@3.2.6@debug/src/node.js
 @ ./node_modules/_debug@3.2.6@debug/src/index.js
 @ ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js
Module not found: Error: Can't resolve 'stream' in 'D:\megalo\my-megalo-pro\node_modules\_follow-redirects@1.7.0@follow-redirects'
 @ ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js 10:15-32
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_debug@3.2.6@debug/src/node.js
Module not found: Error: Can't resolve 'tty' in 'D:\megalo\my-megalo-pro\node_modules\_debug@3.2.6@debug\src'
 @ ./node_modules/_debug@3.2.6@debug/src/node.js 7:10-24
 @ ./node_modules/_debug@3.2.6@debug/src/index.js
 @ ./node_modules/_follow-redirects@1.7.0@follow-redirects/index.js
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

ERROR in ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js
Module not found: Error: Can't resolve 'zlib' in 'D:\megalo\my-megalo-pro\node_modules\_axios@0.18.0@axios\lib\adapters'
 @ ./node_modules/_axios@0.18.0@axios/lib/adapters/http.js 11:11-26
 @ ./node_modules/_axios@0.18.0@axios/lib/defaults.js
 @ ./node_modules/_axios@0.18.0@axios/lib/axios.js
 @ ./node_modules/_axios@0.18.0@axios/index.js
 @ ./src/res/js/webapi.js
 @ ./src/app.js

**Comment by bigmeow** [comment]
仔细阅读文档 https://github.com/bigMeow/axios-miniprogram-adapter/blob/master/doc/api.md
