### ISSUE TITLE
百度小程序的 request，不支持 config.data 为 string 类型

### ISSUE THREAD

**Issue by a573367014** [bigmeow/axios-miniprogram-adapter#3]
### 问题是什么
mpRequestOption.data 是JSON字符串, 在百度不会解析为JSON

### 环境
- 手机: 小米6
- 系统：安卓7.1.1
- 微信版本：6.7.0
- axios-miniprogram-adapter版本：0.1.0
- 其他版本信息

### 在线例子
如果有请提供在线例子

### 其他
其他信息

**Comment by bigmeow** [comment]
问题已修复 @a573367014
