### ISSUE TITLE
偶尔会出现 adapter is not a function。

### ISSUE THREAD

**Issue by LinBoYuanGitHub** [bigmeow/axios-miniprogram-adapter#4]
### 问题是什么
在小程序首页请求接口，偶尔会出现:
TypeError: adapter is not a function
    at dispatchRequest (utils.js:304)
    at <anonymous>

### 环境
- 手机: iPhone X
- 系统：IOS 12.1.4(16D57)
- 微信版本：7.0.3
- axios-miniprogram-adapter版本：0.2.4

**Comment by bigmeow** [comment]
用的原声小程序编写的还是mpvue\megaolo ，还是我的demo

**Comment by LinBoYuanGitHub** [comment]
使用的是native的demo，发现是把 axios.post 放在了原生接口wx.login({success:}) 的回调中出现的。

**Comment by yz1311** [comment]
我也碰到这个问题，wx.login后调用，必然发生

**Comment by bigmeow** [comment]
我在仓库内置的native-demo里加测试代码测试，没有重现你们说的问题，方便弄一个最简单的demo代码放GitHub么
@LinBoYuanGitHub @yz1311 
```js
    wx.login({
      success () {
        axios.post('https://easy-mock.com/mock/5be12b95f7aed41684f2daea/axiosTest/getPersonByPost')
          .then(resp => {
            console.log('Post请求成功:', resp)
          }).catch(({ message, name, config, code, stack, request, response }) => {
            console.log(`捕获到了异常：${message}\n ${name} \n ${config} \n ${code}\n`, request, response)
          })
      }
    })
```

**Comment by techGay** [comment]
> 我在仓库内置的native-demo里加测试代码测试，没有重现你们说的问题，方便弄一个最简单的demo代码放GitHub么
> @LinBoYuanGitHub @yz1311
> 
> ```js
>     wx.login({
>       success () {
>         axios.post('https://easy-mock.com/mock/5be12b95f7aed41684f2daea/axiosTest/getPersonByPost')
>           .then(resp => {
>             console.log('Post请求成功:', resp)
>           }).catch(({ message, name, config, code, stack, request, response }) => {
>             console.log(`捕获到了异常：${message}\n ${name} \n ${config} \n ${code}\n`, request, response)
>           })
>       }
>     })
> ```

typescript 构建工程必现，demo可以使用官方编辑器新建项目，新建的时候语言使用typescript

看了大概是ts构建后转成js时引入由
```javascript
import axios from 'axios'
import mpAdapter from 'axios-miniprogram-adapter'
axios.defaults.adapter = mpAdapter
```
变成了
```javascript
var axios_1 = require("axios");
var axios_miniprogram_adapter_1 = require("axios-miniprogram-adapter");
axios_1.default.defaults.adapter = axios_miniprogram_adapter_1.default;
```
因此导致的吧 @bigmeow

**Comment by bigmeow** [comment]
@techGay  原因是 ts 编译成 js后  ```require("axios-miniprogram-adapter").default```, 多了个`default`,我已经发新版导出了`module.exportts.default = xxx` 兼容了这种情况；
另外，建议项目的 `tsconfig.json`下面2个配置字段改成：
```json
{
   "module": "ESNext",
    "target": "ES2017"
}
```
然后勾选上开发者工具的 `es6==>es5`、 `增强编译`

**Comment by techGay** [comment]
> @techGay 原因是 ts 编译成 js后 `require("axios-miniprogram-adapter").default`, 多了个`default`,我已经发新版导出了`module.exportts.default = xxx` 兼容了这种情况；
> 另外，建议项目的 `tsconfig.json`下面2个配置字段改成：
> 
> ```json
> {
>    "module": "ESNext",
>     "target": "ES2017"
> }
> ```
> 
> 然后勾选上开发者工具的 `es6==>es5`、 `增强编译`

好的，谢谢
