### ISSUE TITLE
请求选项加入dataType参数

### ISSUE THREAD

**Issue by LarenDorr** [bigmeow/axios-miniprogram-adapter#7]
### 问题是什么
`request`选项加入`dataType`参数

`NetworkRequestOpts `中应有`dataType`参数，但是请求的代码里没有附上。https://github.com/bigmeow/axios-miniprogram-adapter/blob/10dc0a36690b46d031c5138669f2a1d552213c7a/src/index.ts#L25

**Comment by bigmeow** [comment]
@LarenDorr  不需要这个参数
1. axios 没有这个参数
2. 小程序官方文档这个参数只有两个值， json 和 string,  默认json；  实际上 如果你的接口返回的数据是json格式的，会被自动parse，如果不是json格式的，则以纯字符串的形式给你，所以这个参数有没有都没有用
